name: bbs-go-server

on: [ push ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Get dependencies
        run: |
          cd server
          go mod download

      - name: Build
        run: |
          cd server
          go build -v .
